### ISSUE TITLE
1号是周日的bug

### ISSUE THREAD

**Issue by jun1362008** [chaosx110/angular-almanac#1]
你好，终于找到一个ng2的农历插件，表示感谢。
提个bug，当1号是周日的时候，这一天会独占一行，前面没有6天空白的占位。

还有，能把节气、节日在日历中显示吗。
还有每月初一能显示当月月份吗，比如“八月初一”这一天则显示“八月”而不是“初一”，如果是闰月能显示闰月那就太完美了，比如“闰八月”。

再次表示感谢。

**Comment by ortizyc** [comment]
1. 1号是周日的bug已经修复
2. 节气节日已经加入
3. 闰月的显示也已经加入
样式未调整，如果有需要可以自己fork后进行项目需求调整
